CREATE TABLE product (
  name VARCHAR(255), 
  description  VARCHAR(255),
  category  VARCHAR(255), 
  price MONEY,
  deleted_at TIME
);

INSERT INTO product (name, description, category, price)
VALUES ('California Roll',
        'Avocado, cucumber, and crab meat rolled in seaweed and rice, served with soy sauce and wasabi.', 'Sushi Roll',
        9.99),
       ('Spicy Tuna Roll',
        'Fresh tuna mixed with spicy mayo, rolled in seaweed and rice, served with soy sauce and pickled ginger.',
        'Sushi Roll', 10.99),
       ('Salmon Nigiri', 'Fresh salmon slices over a bed of sushi rice, served with soy sauce and wasabi.', 'Nigiri',
        8.49),
       ('Tuna Nigiri', 'Fresh tuna slices over a bed of sushi rice, served with soy sauce and wasabi.', 'Nigiri', 9.49),
       ('Green Tea', 'Traditional Japanese green tea, served hot.', 'Beverage', 2.99),
       ('Miso Soup', 'Traditional Japanese soup made with soybean paste, tofu, seaweed, and scallions.', 'Soup', 4.49),
       ('Seaweed Salad',
        'Fresh mixed seaweed tossed in a sesame dressing, served as a refreshing appetizer or side dish.', 'Salad',
        6.49),
       ('Tempura Ice Cream',
        'Vanilla ice cream coated in tempura batter and fried until crispy, served with chocolate sauce.', 'Dessert',
        7.99),
       ('Dragon Roll',
        'Shrimp tempura and cucumber rolled in seaweed and rice, topped with slices of eel and avocado, drizzled with eel sauce, served with soy sauce and wasabi.',
        'Sushi Roll', 15.99),
       ('Edamame', 'Steamed soybeans tossed with sea salt, served as a healthy and delicious appetizer.', 'Appetizer',
        5.99),
       ('Sashimi Platter', 'Assorted fresh slices of fish (tuna, salmon, yellowtail) served with soy sauce and wasabi.',
        'Sashimi', 18.99),
       ('Vegetable Gyoza', 'Pan-fried dumplings filled with assorted vegetables, served with dipping sauce.',
        'Appetizer', 7.99),
       ('Chicken Teriyaki',
        'Grilled chicken breast marinated in teriyaki sauce, served with steamed rice and stir-fried vegetables.',
        'Entree', 14.99),
       ('Tofu Teriyaki',
        'Grilled tofu marinated in teriyaki sauce, served with steamed rice and stir-fried vegetables.', 'Entree',
        12.99),
       ('Shrimp Tempura Roll',
        'Crispy shrimp tempura and avocado rolled in seaweed and rice, served with soy sauce and tempura dipping sauce.',
        'Sushi Roll', 13.99),
       ('Rainbow Roll',
        'Assorted fish (tuna, salmon, yellowtail) and avocado rolled in seaweed and rice, topped with slices of fish and avocado, served with soy sauce and wasabi.',
        'Sushi Roll', 14.99),
       ('Sushi Bento Box',
        'A complete meal with a variety of sushi rolls, nigiri, salad, and miso soup, served in a traditional bento box.',
        'Combination', 17.99),
       ('Sake', 'Japanese rice wine, served cold or hot.', 'Beverage', 8.99),
       ('Chicken Fried Rice', 'Stir-fried rice with chicken, vegetables, and soy sauce, a classic comfort food.',
        'Entree', 12.99),
       ('Beef Teriyaki',
        'Grilled beef sirloin marinated in teriyaki sauce, served with steamed rice and stir-fried vegetables.',
        'Entree', 16.99),
       ('Shrimp Fried Rice', 'Stir-fried rice with shrimp, vegetables, and soy sauce, a delicious and hearty option.',
        'Entree', 14.99),
       ('Vegetable Tempura Roll',
        'Assorted vegetables lightly battered and fried, rolled in seaweed and rice, served with soy sauce and tempura dipping sauce.',
        'Sushi Roll', 11.49),
       ('Salmon Teriyaki',
        'Grilled salmon fillet marinated in teriyaki sauce, served with steamed rice and stir-fried vegetables.',
        'Entree', 19.99),
       ('Beef Fried Rice', 'Stir-fried rice with tender beef, vegetables, and soy sauce, a savory and filling choice.',
        'Entree', 16.99),
       ('Soda', 'Assorted carbonated soft drinks.', 'Beverage', 1.99),
       ('Tuna Tartare',
        'Fresh diced tuna mixed with avocado, cucumber, and spicy mayo, served with crispy wonton chips.', 'Appetizer',
        10.99),
       ('Matcha Cheesecake',
        'Creamy cheesecake flavored with Japanese matcha green tea, served with a drizzle of matcha sauce.', 'Dessert',
        9.99),
       ('Japanese Pancakes', 'Fluffy pancakes served with fresh berries and a dollop of whipped cream.', 'Dessert',
        11.99);
